# -*- mode: ruby -*-
# vi: ft=ruby ts=2 et

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "ubuntu-docker"

  config.vm.provision :shell, path: "install-docker.sh"
    
end
